# Generated by Django 3.0.1 on 2020-03-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200219_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fb_profile_url',
            new_name='profile_url',
        ),
    ]
