# Generated by Django 3.0.1 on 2020-06-27 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0017_invitation'),
        ('gallery', '0002_gallerypermissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallerypermissions',
            unique_together={('user', 'event')},
        ),
    ]
