# Generated by Django 3.0.1 on 2019-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom', models.CharField(max_length=100)),
                ('bride', models.CharField(max_length=100)),
                ('tag_line', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('invite_description', models.CharField(max_length=1000)),
                ('quote', models.CharField(max_length=2000)),
                ('gmap_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
