# Generated by Django 3.0.1 on 2019-12-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191228_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhost',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_hosts', to='event.Event'),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_timeline', to='event.Event'),
        ),
    ]
