# Generated by Django 3.0.1 on 2020-01-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='gmap_link',
            new_name='gmap_location',
        ),
    ]
