# Generated by Django 3.0.1 on 2020-01-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('event', '0006_auto_20200112_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='theme_events', to='themes.Theme'),
        ),
    ]
