# Generated by Django 3.0.1 on 2020-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_themeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeimage',
            name='image_name',
            field=models.CharField(default='image', max_length=50),
            preserve_default=False,
        ),
    ]
