# Generated by Django 3.0.1 on 2020-03-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20200302_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeimage',
            name='user',
        ),
    ]
