# Generated by Django 3.0.1 on 2020-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_themeimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plan',
            field=models.CharField(choices=[('BA', 'Basic Plan'), ('AD', 'Advance Plan'), ('PR', 'Premium Plan')], default='BA', max_length=2),
        ),
    ]
