# Generated by Django 3.0.1 on 2020-07-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
